import {
  ARCHWAY_MAINNET_CHAIN_INFO,
  ARCHWAY_MAINNET_TOKENS_MAP,
  ARCHWAY_TESTNET_CHAIN_INFO,
  ARCHWAY_TESTNET_TOKENS_MAP,
} from "./archway";
import {
  OSMOSIS_MAINNET_CHAIN_INFO,
  OSMOSIS_MAINNET_TOKENS_MAP,
  OSMOSIS_TESTNET_CHAIN_INFO,
  OSMOSIS_TESTNET_TOKENS_MAP,
} from "./osmosis";

import { RegistryToken } from "./types";

export const ALL_CHAINS_TOKEN_MAP: Record<
  string,
  Record<string, RegistryToken>
> = {
  [ARCHWAY_MAINNET_CHAIN_INFO.id]: ARCHWAY_MAINNET_TOKENS_MAP,
  [ARCHWAY_TESTNET_CHAIN_INFO.id]: ARCHWAY_TESTNET_TOKENS_MAP,
  [OSMOSIS_MAINNET_CHAIN_INFO.id]: OSMOSIS_MAINNET_TOKENS_MAP,
  [OSMOSIS_TESTNET_CHAIN_INFO.id]: OSMOSIS_TESTNET_TOKENS_MAP,
};
